services:
  app:
    build: ./app
    links:
    - db
    ports:
    - 8080:8080
  db:
    image: mongo
    ports:
    - 27017:27017
  frontend:
    build: ./frontend
    links:
    - app
    ports:
    - 8000:80
version: "2"
